-- =====================================================================
-- Perfumería · tablas, reglas de acceso y catálogo inicial
-- Pega TODO este archivo en Supabase → SQL Editor → New query → Run
-- Se puede ejecutar más de una vez sin duplicar nada.
-- =====================================================================

-- ---------- Tablas ----------
create table if not exists public.profiles (
  id      uuid primary key references auth.users(id) on delete cascade,
  nombre  text    not null,
  admin   boolean not null default false,
  precios jsonb   not null default '{}'::jsonb      -- precio por unidad que paga al dueño, por tamaño
);

create table if not exists public.config (
  id       int primary key default 1 check (id = 1),
  tamanos  jsonb not null,
  esencias jsonb not null
);

create table if not exists public.perfumes (
  id     uuid primary key default gen_random_uuid(),
  nombre text not null,
  genero text not null default '',
  tipo   text not null default 'clasica',
  bodega int  not null default 0
);

create table if not exists public.entregas (
  id    uuid primary key default gen_random_uuid(),
  vid   uuid not null references public.profiles(id) on delete cascade,
  tipo  text not null default 'entrega',               -- entrega | devolucion
  fecha timestamptz not null default now(),
  items jsonb not null                                  -- [{pid, ml, cant}]
);

create table if not exists public.ventas (
  id      uuid primary key default gen_random_uuid(),
  num     bigint generated by default as identity,     -- número del comprobante
  vid     uuid not null references public.profiles(id) on delete cascade,
  fecha   timestamptz not null default now(),
  cliente text not null,
  items   jsonb not null,                               -- [{pid, ml, cant, precio}]
  total   numeric not null,
  abonos  jsonb not null default '[]'::jsonb            -- [{fecha, monto}]
);

create table if not exists public.pagos (
  id    uuid primary key default gen_random_uuid(),
  vid   uuid not null references public.profiles(id) on delete cascade,
  fecha timestamptz not null default now(),
  monto numeric not null,
  nota  text not null default ''
);

-- ---------- Funciones de apoyo ----------
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select admin from public.profiles where id = auth.uid()), false)
$$;

create or replace function public.has_profile() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid())
$$;

create or replace function public.hay_perfiles() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles)
$$;

-- Un vendedor no puede vender más de lo que se le entregó (validación en el servidor)
create or replace function public.validar_stock() returns trigger
language plpgsql security definer set search_path = public as $$
declare r record; tengo int;
begin
  for r in
    select it->>'pid' as pid, (it->>'ml')::int as ml, sum((it->>'cant')::int)::int as necesito
    from jsonb_array_elements(new.items) as it
    group by 1, 2
  loop
    select coalesce((select sum(case when e.tipo = 'devolucion' then -(x->>'cant')::int else (x->>'cant')::int end)
                     from public.entregas e, jsonb_array_elements(e.items) as x
                     where e.vid = new.vid and x->>'pid' = r.pid and (x->>'ml')::int = r.ml), 0)
         - coalesce((select sum((y->>'cant')::int)
                     from public.ventas v, jsonb_array_elements(v.items) as y
                     where v.vid = new.vid and v.id <> new.id and y->>'pid' = r.pid and (y->>'ml')::int = r.ml), 0)
    into tengo;
    if tengo < r.necesito then
      raise exception 'No tienes suficiente de ese perfume en % ml (te quedan %, intentas vender %).', r.ml, tengo, r.necesito;
    end if;
  end loop;
  return new;
end $$;

drop trigger if exists trg_validar_stock on public.ventas;
create trigger trg_validar_stock before insert on public.ventas
  for each row execute function public.validar_stock();

-- ---------- Seguridad por filas (RLS) ----------
alter table public.profiles enable row level security;
alter table public.config   enable row level security;
alter table public.perfumes enable row level security;
alter table public.entregas enable row level security;
alter table public.ventas   enable row level security;
alter table public.pagos    enable row level security;

drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists profiles_delete on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy profiles_insert on public.profiles for insert to authenticated
  with check (public.is_admin() or (id = auth.uid() and admin and not public.hay_perfiles()));   -- el primer usuario crea al dueño
create policy profiles_update on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy profiles_delete on public.profiles for delete to authenticated using (public.is_admin());

drop policy if exists config_select on public.config;
drop policy if exists config_write  on public.config;
create policy config_select on public.config for select to authenticated using (public.has_profile());
create policy config_write  on public.config for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists perfumes_select on public.perfumes;
drop policy if exists perfumes_write  on public.perfumes;
create policy perfumes_select on public.perfumes for select to authenticated using (public.has_profile());
create policy perfumes_write  on public.perfumes for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists entregas_select on public.entregas;
drop policy if exists entregas_write  on public.entregas;
create policy entregas_select on public.entregas for select to authenticated using (vid = auth.uid() or public.is_admin());
create policy entregas_write  on public.entregas for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists ventas_all on public.ventas;
create policy ventas_all on public.ventas for all to authenticated
  using (vid = auth.uid() or public.is_admin()) with check (vid = auth.uid() or public.is_admin());

drop policy if exists pagos_select on public.pagos;
drop policy if exists pagos_write  on public.pagos;
create policy pagos_select on public.pagos for select to authenticated using (vid = auth.uid() or public.is_admin());
create policy pagos_write  on public.pagos for all    to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Permisos ----------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.hay_perfiles() to anon, authenticated;

-- ---------- Datos iniciales ----------
insert into public.config (id, tamanos, esencias) values (
  1,
  '[{"ml":30,"precio":20000},{"ml":50,"precio":40000},{"ml":100,"precio":65000}]',
  '{"clasica":{"onza":8000,"g100":25000},"premium":{"onza":12000,"g100":35000}}'
) on conflict (id) do nothing;

insert into public.perfumes (nombre, genero, tipo, bodega)
select * from (values
  ('Solo', '', 'clasica', 0),
  ('Ohm', 'Hombre', 'clasica', 2),
  ('Yum Yum', 'Hombre', 'premium', 3),
  ('9pm Elixir', '', 'clasica', 1),
  ('9pm Rebel', 'Hombre', 'premium', 3),
  ('Arabians Tonka', 'Hombre', 'premium', 2),
  ('212 Vip Men', 'Hombre', 'clasica', 1),
  ('212 Vip Black Men', 'Hombre', 'clasica', 1),
  ('Jean Paul Elixir', 'Hombre', 'clasica', 1),
  ('Jean Paul Le Male', '', 'clasica', 0),
  ('Bond Signature', '', 'clasica', 0),
  ('Bond Bleecker Street', '', 'clasica', 0),
  ('Amber Royal', '', 'clasica', 2),
  ('Amber Pis Aqua Dubai', '', 'clasica', 0),
  ('Creed Irish Tweed', '', 'clasica', 0),
  ('Creed Adventus', '', 'clasica', 0),
  ('Creed Silver', 'Unisex', 'clasica', 2),
  ('Tommy Men', 'Hombre', 'clasica', 2),
  ('360 Men', 'Hombre', 'clasica', 3),
  ('360 Fem', 'Mujer', 'clasica', 0),
  ('Khamrah', '', 'clasica', 2),
  ('Khamrah Dukhan', '', 'clasica', 0),
  ('Khamrah Qahwa', '', 'clasica', 0),
  ('Messi', '', 'clasica', 0),
  ('Lacoste Blue', '', 'clasica', 2),
  ('Paris Hilton Fem', 'Mujer', 'clasica', 5),
  ('La Vida Es Bella', '', 'clasica', 0),
  ('Korbaj Tóxico Desire', '', 'clasica', 0),
  ('Bharara King', '', 'clasica', 0),
  ('Dubai Night', '', 'clasica', 0),
  ('Hawas Malibú', '', 'clasica', 0),
  ('Hawas Kobra', '', 'clasica', 0),
  ('Odyssey Candee Fem', 'Mujer', 'clasica', 0),
  ('Mandarín Sky', '', 'clasica', 2),
  ('Issey Miyake', '', 'clasica', 0),
  ('Aqua De Gio', 'Hombre', 'clasica', 3),
  ('Amber Rouge', 'Unisex', 'clasica', 4),
  ('Il Rosso', '', 'clasica', 2),
  ('Oud Saffron', 'Unisex', 'premium', 2),
  ('Olympea Fem', 'Mujer', 'clasica', 4),
  ('Ralph Fem', 'Mujer', 'clasica', 1),
  ('Honor Y Glory', '', 'clasica', 6),
  ('Valentino Donna Born In Roma', 'Hombre', 'premium', 2),
  ('Valentino Donna Born In Roma Intense', 'Hombre', 'premium', 2),
  ('Lacoste Blanca', 'Hombre', 'clasica', 3),
  ('Sublime', '', 'clasica', 6),
  ('Valentino Men', '', 'clasica', 0),
  ('Swiss Army', 'Hombre', 'clasica', 4),
  ('One Million', 'Hombre', 'clasica', 2),
  ('Invictus Victory', 'Hombre', 'clasica', 3),
  ('Ombre Nomade', 'Hombre', 'premium', 3)
) as v(nombre, genero, tipo, bodega)
where not exists (select 1 from public.perfumes);
